### ISSUE TITLE
Ngrok integration

### ISSUE THREAD

**Issue by Vincz** [Elao/symfony-standard#12]
Partant du principe que les VM sont des linux supposés propres et que l'on a une seule VM par projet. Il pourrait être pratique d'intégrer nativement ngrok dans nos distributions. 
Par exemple, sur mon projet, j'ai installé ngrok dans ma VM avec le fichier de configuration suivant:

```
auth_token: TroooopSecret
tunnels:
  project-name:
    subdomain: "elao-project-name"
    proto:
        http: 80
```

Ce qui me permet de lancer tout simplement:
    ngrok start project-name
pour avoir une url accessible de l'exterieur de la forme : elao-project-name.ngrok.com
Ce qui est très pratique pour les démos, ou simplement pour exposer sa version local aux autres développeurs.
